import 'package:meta/meta.dart';

import '../../common/copy_with_sentinel.dart';
import '../../common/equality_helpers.dart';

/// Token usage for a single model request.
@immutable
class SpanModelUsage {
  /// Input tokens consumed by this request.
  final int inputTokens;

  /// Output tokens generated by this request.
  final int outputTokens;

  /// Tokens used to create prompt cache in this request.
  final int cacheCreationInputTokens;

  /// Tokens read from prompt cache in this request.
  final int cacheReadInputTokens;

  /// Inference speed tier this request ran at.
  final String? speed;

  /// Creates a [SpanModelUsage].
  const SpanModelUsage({
    required this.inputTokens,
    required this.outputTokens,
    required this.cacheCreationInputTokens,
    required this.cacheReadInputTokens,
    this.speed,
  });

  /// Creates a [SpanModelUsage] from JSON.
  factory SpanModelUsage.fromJson(Map<String, dynamic> json) {
    return SpanModelUsage(
      inputTokens: json['input_tokens'] as int,
      outputTokens: json['output_tokens'] as int,
      cacheCreationInputTokens: json['cache_creation_input_tokens'] as int,
      cacheReadInputTokens: json['cache_read_input_tokens'] as int,
      speed: json['speed'] as String?,
    );
  }

  /// Converts to JSON.
  Map<String, dynamic> toJson() => {
    'input_tokens': inputTokens,
    'output_tokens': outputTokens,
    'cache_creation_input_tokens': cacheCreationInputTokens,
    'cache_read_input_tokens': cacheReadInputTokens,
    if (speed != null) 'speed': speed,
  };

  /// Creates a copy with replaced values.
  SpanModelUsage copyWith({
    int? inputTokens,
    int? outputTokens,
    int? cacheCreationInputTokens,
    int? cacheReadInputTokens,
    Object? speed = unsetCopyWithValue,
  }) {
    return SpanModelUsage(
      inputTokens: inputTokens ?? this.inputTokens,
      outputTokens: outputTokens ?? this.outputTokens,
      cacheCreationInputTokens:
          cacheCreationInputTokens ?? this.cacheCreationInputTokens,
      cacheReadInputTokens: cacheReadInputTokens ?? this.cacheReadInputTokens,
      speed: speed == unsetCopyWithValue ? this.speed : speed as String?,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SpanModelUsage &&
          runtimeType == other.runtimeType &&
          inputTokens == other.inputTokens &&
          outputTokens == other.outputTokens &&
          cacheCreationInputTokens == other.cacheCreationInputTokens &&
          cacheReadInputTokens == other.cacheReadInputTokens &&
          speed == other.speed;

  @override
  int get hashCode => Object.hash(
    inputTokens,
    outputTokens,
    cacheCreationInputTokens,
    cacheReadInputTokens,
    speed,
  );

  @override
  String toString() =>
      'SpanModelUsage('
      'inputTokens: $inputTokens, '
      'outputTokens: $outputTokens, '
      'cacheCreationInputTokens: $cacheCreationInputTokens, '
      'cacheReadInputTokens: $cacheReadInputTokens, '
      'speed: $speed)';
}

/// Prompt-cache creation token usage broken down by cache lifetime.
@immutable
class CacheCreationUsage {
  /// Tokens used to create 5-minute ephemeral cache entries.
  final int? ephemeral5mInputTokens;

  /// Tokens used to create 1-hour ephemeral cache entries.
  final int? ephemeral1hInputTokens;

  /// Creates a [CacheCreationUsage].
  const CacheCreationUsage({
    this.ephemeral5mInputTokens,
    this.ephemeral1hInputTokens,
  });

  /// Creates a [CacheCreationUsage] from JSON.
  factory CacheCreationUsage.fromJson(Map<String, dynamic> json) {
    return CacheCreationUsage(
      ephemeral5mInputTokens: json['ephemeral_5m_input_tokens'] as int?,
      ephemeral1hInputTokens: json['ephemeral_1h_input_tokens'] as int?,
    );
  }

  /// Converts to JSON.
  Map<String, dynamic> toJson() => {
    if (ephemeral5mInputTokens != null)
      'ephemeral_5m_input_tokens': ephemeral5mInputTokens,
    if (ephemeral1hInputTokens != null)
      'ephemeral_1h_input_tokens': ephemeral1hInputTokens,
  };

  /// Creates a copy with replaced values.
  CacheCreationUsage copyWith({
    Object? ephemeral5mInputTokens = unsetCopyWithValue,
    Object? ephemeral1hInputTokens = unsetCopyWithValue,
  }) {
    return CacheCreationUsage(
      ephemeral5mInputTokens: ephemeral5mInputTokens == unsetCopyWithValue
          ? this.ephemeral5mInputTokens
          : ephemeral5mInputTokens as int?,
      ephemeral1hInputTokens: ephemeral1hInputTokens == unsetCopyWithValue
          ? this.ephemeral1hInputTokens
          : ephemeral1hInputTokens as int?,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CacheCreationUsage &&
          runtimeType == other.runtimeType &&
          ephemeral5mInputTokens == other.ephemeral5mInputTokens &&
          ephemeral1hInputTokens == other.ephemeral1hInputTokens;

  @override
  int get hashCode =>
      Object.hash(ephemeral5mInputTokens, ephemeral1hInputTokens);

  @override
  String toString() =>
      'CacheCreationUsage('
      'ephemeral5mInputTokens: $ephemeral5mInputTokens, '
      'ephemeral1hInputTokens: $ephemeral1hInputTokens)';
}

/// What the client should do next in response to a session error.
///
/// Variants:
/// - [RetryStatusRetrying] — server is retrying automatically.
/// - [RetryStatusExhausted] — turn is dead; client may send a new prompt.
/// - [RetryStatusTerminal] — session will transition to terminated state.
/// - [UnknownRetryStatus] — unrecognized status; preserves raw JSON.
sealed class RetryStatus {
  const RetryStatus();

  /// Creates a [RetryStatus] from JSON.
  factory RetryStatus.fromJson(Map<String, dynamic> json) {
    final type = json['type'] as String;
    return switch (type) {
      'retrying' => RetryStatusRetrying.fromJson(json),
      'exhausted' => RetryStatusExhausted.fromJson(json),
      'terminal' => RetryStatusTerminal.fromJson(json),
      _ => UnknownRetryStatus(rawJson: json),
    };
  }

  /// Converts to JSON.
  Map<String, dynamic> toJson();
}

/// The server is retrying automatically.
@immutable
class RetryStatusRetrying extends RetryStatus {
  /// The type discriminator. Always `retrying`.
  final String type;

  /// Creates a [RetryStatusRetrying].
  const RetryStatusRetrying({this.type = 'retrying'});

  /// Creates a [RetryStatusRetrying] from JSON.
  factory RetryStatusRetrying.fromJson(Map<String, dynamic> json) {
    return RetryStatusRetrying(type: json['type'] as String? ?? 'retrying');
  }

  @override
  Map<String, dynamic> toJson() => {'type': type};

  /// Creates a copy with replaced values.
  RetryStatusRetrying copyWith({String? type}) {
    return RetryStatusRetrying(type: type ?? this.type);
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RetryStatusRetrying &&
          runtimeType == other.runtimeType &&
          type == other.type;

  @override
  int get hashCode => type.hashCode;

  @override
  String toString() => 'RetryStatusRetrying(type: $type)';
}

/// The turn is dead; queued inputs are flushed.
@immutable
class RetryStatusExhausted extends RetryStatus {
  /// The type discriminator. Always `exhausted`.
  final String type;

  /// Creates a [RetryStatusExhausted].
  const RetryStatusExhausted({this.type = 'exhausted'});

  /// Creates a [RetryStatusExhausted] from JSON.
  factory RetryStatusExhausted.fromJson(Map<String, dynamic> json) {
    return RetryStatusExhausted(type: json['type'] as String? ?? 'exhausted');
  }

  @override
  Map<String, dynamic> toJson() => {'type': type};

  /// Creates a copy with replaced values.
  RetryStatusExhausted copyWith({String? type}) {
    return RetryStatusExhausted(type: type ?? this.type);
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RetryStatusExhausted &&
          runtimeType == other.runtimeType &&
          type == other.type;

  @override
  int get hashCode => type.hashCode;

  @override
  String toString() => 'RetryStatusExhausted(type: $type)';
}

/// The session encountered a terminal error and will transition to terminated.
@immutable
class RetryStatusTerminal extends RetryStatus {
  /// The type discriminator. Always `terminal`.
  final String type;

  /// Creates a [RetryStatusTerminal].
  const RetryStatusTerminal({this.type = 'terminal'});

  /// Creates a [RetryStatusTerminal] from JSON.
  factory RetryStatusTerminal.fromJson(Map<String, dynamic> json) {
    return RetryStatusTerminal(type: json['type'] as String? ?? 'terminal');
  }

  @override
  Map<String, dynamic> toJson() => {'type': type};

  /// Creates a copy with replaced values.
  RetryStatusTerminal copyWith({String? type}) {
    return RetryStatusTerminal(type: type ?? this.type);
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RetryStatusTerminal &&
          runtimeType == other.runtimeType &&
          type == other.type;

  @override
  int get hashCode => type.hashCode;

  @override
  String toString() => 'RetryStatusTerminal(type: $type)';
}

/// Unrecognized retry status — preserves raw JSON.
@immutable
class UnknownRetryStatus extends RetryStatus {
  /// The raw JSON.
  final Map<String, dynamic> rawJson;

  /// Creates an [UnknownRetryStatus].
  const UnknownRetryStatus({required this.rawJson});

  @override
  Map<String, dynamic> toJson() => rawJson;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UnknownRetryStatus &&
          runtimeType == other.runtimeType &&
          mapsDeepEqual(rawJson, other.rawJson);

  @override
  int get hashCode => mapDeepHashCode(rawJson);

  @override
  String toString() => 'UnknownRetryStatus(rawJson: $rawJson)';
}
