import 'package:meta/meta.dart';

import '../common/copy_with_sentinel.dart';
import '../common/equality_helpers.dart';
import '../tools/tool_caller.dart';

/// Content block in a response message.
///
/// Response content blocks represent different types of content
/// generated by the model. Unknown types are preserved as
/// [UnknownContentBlock] for forward compatibility.
sealed class ContentBlock {
  const ContentBlock();

  /// Creates a [ContentBlock] from JSON.
  factory ContentBlock.fromJson(Map<String, dynamic> json) {
    final type = json['type'] as String;
    return switch (type) {
      'text' => TextBlock.fromJson(json),
      'thinking' => ThinkingBlock.fromJson(json),
      'redacted_thinking' => RedactedThinkingBlock.fromJson(json),
      'tool_use' => ToolUseBlock.fromJson(json),
      'server_tool_use' => ServerToolUseBlock.fromJson(json),
      'web_search_tool_result' => WebSearchToolResultBlock.fromJson(json),
      'web_fetch_tool_result' => WebFetchToolResultBlock.fromJson(json),
      'code_execution_tool_result' => CodeExecutionToolResultBlock.fromJson(
        json,
      ),
      'bash_code_execution_tool_result' =>
        BashCodeExecutionToolResultBlock.fromJson(json),
      'text_editor_code_execution_tool_result' =>
        TextEditorCodeExecutionToolResultBlock.fromJson(json),
      'tool_search_tool_result' => ToolSearchToolResultBlock.fromJson(json),
      'container_upload' => ContainerUploadBlock.fromJson(json),
      'compaction' => CompactionBlock.fromJson(json),
      'mcp_tool_use' => MCPToolUseBlock.fromJson(json),
      'mcp_tool_result' => MCPToolResultBlock.fromJson(json),
      'advisor_tool_result' => AdvisorToolResultBlock.fromJson(json),
      _ => UnknownContentBlock.fromJson(json),
    };
  }

  /// Converts to JSON.
  Map<String, dynamic> toJson();
}

/// Text content block in a response.
@immutable
class TextBlock extends ContentBlock {
  /// The text content.
  final String text;

  /// Citations supporting this text block.
  final List<Citation>? citations;

  /// Creates a [TextBlock].
  const TextBlock({required this.text, this.citations});

  /// Creates a [TextBlock] from JSON.
  factory TextBlock.fromJson(Map<String, dynamic> json) {
    return TextBlock(
      text: json['text'] as String,
      citations: (json['citations'] as List?)
          ?.map((e) => Citation.fromJson(e as Map<String, dynamic>))
          .toList(),
    );
  }

  @override
  Map<String, dynamic> toJson() => {
    'type': 'text',
    'text': text,
    if (citations != null)
      'citations': citations!.map((e) => e.toJson()).toList(),
  };

  /// Creates a copy with replaced values.
  TextBlock copyWith({String? text, Object? citations = unsetCopyWithValue}) {
    return TextBlock(
      text: text ?? this.text,
      citations: citations == unsetCopyWithValue
          ? this.citations
          : citations as List<Citation>?,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextBlock &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          listsEqual(citations, other.citations);

  @override
  int get hashCode => Object.hash(text, listHash(citations));

  @override
  String toString() =>
      'TextBlock(text: [${text.length} chars], citations: $citations)';
}

/// Thinking (reasoning) content block in a response.
@immutable
class ThinkingBlock extends ContentBlock {
  /// The thinking/reasoning content.
  final String thinking;

  /// Signature for the thinking block.
  final String signature;

  /// Creates a [ThinkingBlock].
  const ThinkingBlock({required this.thinking, required this.signature});

  /// Creates a [ThinkingBlock] from JSON.
  factory ThinkingBlock.fromJson(Map<String, dynamic> json) {
    return ThinkingBlock(
      thinking: json['thinking'] as String,
      signature: json['signature'] as String,
    );
  }

  @override
  Map<String, dynamic> toJson() => {
    'type': 'thinking',
    'thinking': thinking,
    'signature': signature,
  };

  /// Creates a copy with replaced values.
  ThinkingBlock copyWith({String? thinking, String? signature}) {
    return ThinkingBlock(
      thinking: thinking ?? this.thinking,
      signature: signature ?? this.signature,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ThinkingBlock &&
          runtimeType == other.runtimeType &&
          thinking == other.thinking &&
          signature == other.signature;

  @override
  int get hashCode => Object.hash(thinking, signature);

  @override
  String toString() =>
      'ThinkingBlock(thinking: [${thinking.length} chars], '
      'signature: [${signature.length} chars])';
}

/// Redacted thinking block (when thinking content is not available).
@immutable
class RedactedThinkingBlock extends ContentBlock {
  /// Opaque data for the redacted content.
  final String data;

  /// Creates a [RedactedThinkingBlock].
  const RedactedThinkingBlock({required this.data});

  /// Creates a [RedactedThinkingBlock] from JSON.
  factory RedactedThinkingBlock.fromJson(Map<String, dynamic> json) {
    return RedactedThinkingBlock(data: json['data'] as String);
  }

  @override
  Map<String, dynamic> toJson() => {'type': 'redacted_thinking', 'data': data};

  /// Creates a copy with replaced values.
  RedactedThinkingBlock copyWith({String? data}) {
    return RedactedThinkingBlock(data: data ?? this.data);
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RedactedThinkingBlock &&
          runtimeType == other.runtimeType &&
          data == other.data;

  @override
  int get hashCode => data.hashCode;

  @override
  String toString() => 'RedactedThinkingBlock(data: [${data.length} chars])';
}

/// Tool use block in a response.
@immutable
class ToolUseBlock extends ContentBlock {
  /// Unique identifier for this tool use.
  final String id;

  /// Name of the tool being used.
  final String name;

  /// Input parameters for the tool.
  final Map<String, dynamic> input;

  /// Caller metadata for this tool invocation.
  final ToolCaller? caller;

  /// Creates a [ToolUseBlock].
  const ToolUseBlock({
    required this.id,
    required this.name,
    required this.input,
    this.caller,
  });

  /// Creates a [ToolUseBlock] from JSON.
  factory ToolUseBlock.fromJson(Map<String, dynamic> json) {
    return ToolUseBlock(
      id: json['id'] as String,
      name: json['name'] as String,
      input: json['input'] as Map<String, dynamic>,
      caller: json['caller'] != null
          ? ToolCaller.fromJson(json['caller'] as Map<String, dynamic>)
          : null,
    );
  }

  @override
  Map<String, dynamic> toJson() => {
    'type': 'tool_use',
    'id': id,
    'name': name,
    'input': input,
    if (caller != null) 'caller': caller!.toJson(),
  };

  /// Creates a copy with replaced values.
  ToolUseBlock copyWith({
    String? id,
    String? name,
    Map<String, dynamic>? input,
    Object? caller = unsetCopyWithValue,
  }) {
    return ToolUseBlock(
      id: id ?? this.id,
      name: name ?? this.name,
      input: input ?? this.input,
      caller: caller == unsetCopyWithValue
          ? this.caller
          : caller as ToolCaller?,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ToolUseBlock &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          mapsEqual(input, other.input) &&
          caller == other.caller;

  @override
  int get hashCode => Object.hash(id, name, mapHash(input), caller);

  @override
  String toString() =>
      'ToolUseBlock(id: $id, name: $name, input: $input, caller: $caller)';
}

/// Server-side tool use block (e.g., web search).
@immutable
class ServerToolUseBlock extends ContentBlock {
  /// Unique identifier for this tool use.
  final String id;

  /// Name of the server tool (e.g., "web_search").
  final String name;

  /// Input parameters for the tool.
  final Map<String, dynamic> input;

  /// Caller metadata for this tool invocation.
  final ToolCaller? caller;

  /// Creates a [ServerToolUseBlock].
  const ServerToolUseBlock({
    required this.id,
    required this.name,
    required this.input,
    this.caller,
  });

  /// Creates a [ServerToolUseBlock] from JSON.
  factory ServerToolUseBlock.fromJson(Map<String, dynamic> json) {
    return ServerToolUseBlock(
      id: json['id'] as String,
      name: json['name'] as String,
      input: json['input'] as Map<String, dynamic>,
      caller: json['caller'] != null
          ? ToolCaller.fromJson(json['caller'] as Map<String, dynamic>)
          : null,
    );
  }

  @override
  Map<String, dynamic> toJson() => {
    'type': 'server_tool_use',
    'id': id,
    'name': name,
    'input': input,
    if (caller != null) 'caller': caller!.toJson(),
  };

  /// Creates a copy with replaced values.
  ServerToolUseBlock copyWith({
    String? id,
    String? name,
    Map<String, dynamic>? input,
    Object? caller = unsetCopyWithValue,
  }) {
    return ServerToolUseBlock(
      id: id ?? this.id,
      name: name ?? this.name,
      input: input ?? this.input,
      caller: caller == unsetCopyWithValue
          ? this.caller
          : caller as ToolCaller?,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerToolUseBlock &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          mapsEqual(input, other.input) &&
          caller == other.caller;

  @override
  int get hashCode => Object.hash(id, name, mapHash(input), caller);

  @override
  String toString() =>
      'ServerToolUseBlock(id: $id, name: $name, input: $input, '
      'caller: $caller)';
}

/// Web search tool result block.
@immutable
class WebSearchToolResultBlock extends ContentBlock {
  /// The tool use ID this result corresponds to.
  final String toolUseId;

  /// The search results content.
  final WebSearchResult content;

  /// Caller metadata for this tool result.
  final ToolCaller? caller;

  /// Creates a [WebSearchToolResultBlock].
  const WebSearchToolResultBlock({
    required this.toolUseId,
    required this.content,
    this.caller,
  });

  /// Creates a [WebSearchToolResultBlock] from JSON.
  factory WebSearchToolResultBlock.fromJson(Map<String, dynamic> json) {
    return WebSearchToolResultBlock(
      toolUseId: json['tool_use_id'] as String,
      content: WebSearchResult.fromJson(json['content'] as Object),
      caller: json['caller'] != null
          ? ToolCaller.fromJson(json['caller'] as Map<String, dynamic>)
          : null,
    );
  }

  @override
  Map<String, dynamic> toJson() => {
    'type': 'web_search_tool_result',
    'tool_use_id': toolUseId,
    'content': content.toJson(),
    if (caller != null) 'caller': caller!.toJson(),
  };

  /// Creates a copy with replaced values.
  WebSearchToolResultBlock copyWith({
    String? toolUseId,
    WebSearchResult? content,
    Object? caller = unsetCopyWithValue,
  }) {
    return WebSearchToolResultBlock(
      toolUseId: toolUseId ?? this.toolUseId,
      content: content ?? this.content,
      caller: caller == unsetCopyWithValue
          ? this.caller
          : caller as ToolCaller?,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebSearchToolResultBlock &&
          runtimeType == other.runtimeType &&
          toolUseId == other.toolUseId &&
          content == other.content &&
          caller == other.caller;

  @override
  int get hashCode => Object.hash(toolUseId, content, caller);

  @override
  String toString() =>
      'WebSearchToolResultBlock(toolUseId: $toolUseId, content: $content, '
      'caller: $caller)';
}

/// Web fetch tool result block.
@immutable
class WebFetchToolResultBlock extends ContentBlock {
  /// The tool use ID this result corresponds to.
  final String toolUseId;

  /// Caller metadata for this tool result.
  final ToolCaller? caller;

  /// Tool result content payload.
  final Map<String, dynamic> content;

  /// Creates a [WebFetchToolResultBlock].
  const WebFetchToolResultBlock({
    required this.toolUseId,
    required this.content,
    this.caller,
  });

  /// Creates a [WebFetchToolResultBlock] from JSON.
  factory WebFetchToolResultBlock.fromJson(Map<String, dynamic> json) {
    return WebFetchToolResultBlock(
      toolUseId: json['tool_use_id'] as String,
      content: (json['content'] as Map).cast<String, dynamic>(),
      caller: json['caller'] != null
          ? ToolCaller.fromJson(json['caller'] as Map<String, dynamic>)
          : null,
    );
  }

  @override
  Map<String, dynamic> toJson() => {
    'type': 'web_fetch_tool_result',
    'tool_use_id': toolUseId,
    'content': content,
    if (caller != null) 'caller': caller!.toJson(),
  };

  /// Creates a copy with replaced values.
  WebFetchToolResultBlock copyWith({
    String? toolUseId,
    Map<String, dynamic>? content,
    Object? caller = unsetCopyWithValue,
  }) {
    return WebFetchToolResultBlock(
      toolUseId: toolUseId ?? this.toolUseId,
      content: content ?? this.content,
      caller: caller == unsetCopyWithValue
          ? this.caller
          : caller as ToolCaller?,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebFetchToolResultBlock &&
          runtimeType == other.runtimeType &&
          toolUseId == other.toolUseId &&
          mapsEqual(content, other.content) &&
          caller == other.caller;

  @override
  int get hashCode => Object.hash(toolUseId, mapHash(content), caller);

  @override
  String toString() =>
      'WebFetchToolResultBlock(toolUseId: $toolUseId, content: $content, '
      'caller: $caller)';
}

/// Code execution tool result block.
@immutable
class CodeExecutionToolResultBlock extends ContentBlock {
  /// The tool use ID this result corresponds to.
  final String toolUseId;

  /// Tool result content payload.
  final Map<String, dynamic> content;

  /// Creates a [CodeExecutionToolResultBlock].
  const CodeExecutionToolResultBlock({
    required this.toolUseId,
    required this.content,
  });

  /// Creates a [CodeExecutionToolResultBlock] from JSON.
  factory CodeExecutionToolResultBlock.fromJson(Map<String, dynamic> json) {
    return CodeExecutionToolResultBlock(
      toolUseId: json['tool_use_id'] as String,
      content: (json['content'] as Map).cast<String, dynamic>(),
    );
  }

  @override
  Map<String, dynamic> toJson() => {
    'type': 'code_execution_tool_result',
    'tool_use_id': toolUseId,
    'content': content,
  };

  /// Creates a copy with replaced values.
  CodeExecutionToolResultBlock copyWith({
    String? toolUseId,
    Map<String, dynamic>? content,
  }) {
    return CodeExecutionToolResultBlock(
      toolUseId: toolUseId ?? this.toolUseId,
      content: content ?? this.content,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CodeExecutionToolResultBlock &&
          runtimeType == other.runtimeType &&
          toolUseId == other.toolUseId &&
          mapsEqual(content, other.content);

  @override
  int get hashCode => Object.hash(toolUseId, mapHash(content));

  @override
  String toString() =>
      'CodeExecutionToolResultBlock(toolUseId: $toolUseId, content: $content)';
}

/// Bash code execution tool result block.
@immutable
class BashCodeExecutionToolResultBlock extends ContentBlock {
  /// The tool use ID this result corresponds to.
  final String toolUseId;

  /// Tool result content payload.
  final Map<String, dynamic> content;

  /// Creates a [BashCodeExecutionToolResultBlock].
  const BashCodeExecutionToolResultBlock({
    required this.toolUseId,
    required this.content,
  });

  /// Creates a [BashCodeExecutionToolResultBlock] from JSON.
  factory BashCodeExecutionToolResultBlock.fromJson(Map<String, dynamic> json) {
    return BashCodeExecutionToolResultBlock(
      toolUseId: json['tool_use_id'] as String,
      content: (json['content'] as Map).cast<String, dynamic>(),
    );
  }

  @override
  Map<String, dynamic> toJson() => {
    'type': 'bash_code_execution_tool_result',
    'tool_use_id': toolUseId,
    'content': content,
  };

  /// Creates a copy with replaced values.
  BashCodeExecutionToolResultBlock copyWith({
    String? toolUseId,
    Map<String, dynamic>? content,
  }) {
    return BashCodeExecutionToolResultBlock(
      toolUseId: toolUseId ?? this.toolUseId,
      content: content ?? this.content,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BashCodeExecutionToolResultBlock &&
          runtimeType == other.runtimeType &&
          toolUseId == other.toolUseId &&
          mapsEqual(content, other.content);

  @override
  int get hashCode => Object.hash(toolUseId, mapHash(content));

  @override
  String toString() =>
      'BashCodeExecutionToolResultBlock(toolUseId: $toolUseId, '
      'content: $content)';
}

/// Text editor code execution tool result block.
@immutable
class TextEditorCodeExecutionToolResultBlock extends ContentBlock {
  /// The tool use ID this result corresponds to.
  final String toolUseId;

  /// Tool result content payload.
  final Map<String, dynamic> content;

  /// Creates a [TextEditorCodeExecutionToolResultBlock].
  const TextEditorCodeExecutionToolResultBlock({
    required this.toolUseId,
    required this.content,
  });

  /// Creates a [TextEditorCodeExecutionToolResultBlock] from JSON.
  factory TextEditorCodeExecutionToolResultBlock.fromJson(
    Map<String, dynamic> json,
  ) {
    return TextEditorCodeExecutionToolResultBlock(
      toolUseId: json['tool_use_id'] as String,
      content: (json['content'] as Map).cast<String, dynamic>(),
    );
  }

  @override
  Map<String, dynamic> toJson() => {
    'type': 'text_editor_code_execution_tool_result',
    'tool_use_id': toolUseId,
    'content': content,
  };

  /// Creates a copy with replaced values.
  TextEditorCodeExecutionToolResultBlock copyWith({
    String? toolUseId,
    Map<String, dynamic>? content,
  }) {
    return TextEditorCodeExecutionToolResultBlock(
      toolUseId: toolUseId ?? this.toolUseId,
      content: content ?? this.content,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextEditorCodeExecutionToolResultBlock &&
          runtimeType == other.runtimeType &&
          toolUseId == other.toolUseId &&
          mapsEqual(content, other.content);

  @override
  int get hashCode => Object.hash(toolUseId, mapHash(content));

  @override
  String toString() =>
      'TextEditorCodeExecutionToolResultBlock(toolUseId: $toolUseId, '
      'content: $content)';
}

/// Tool search tool result block.
@immutable
class ToolSearchToolResultBlock extends ContentBlock {
  /// The tool use ID this result corresponds to.
  final String toolUseId;

  /// Tool result content payload.
  final Map<String, dynamic> content;

  /// Creates a [ToolSearchToolResultBlock].
  const ToolSearchToolResultBlock({
    required this.toolUseId,
    required this.content,
  });

  /// Creates a [ToolSearchToolResultBlock] from JSON.
  factory ToolSearchToolResultBlock.fromJson(Map<String, dynamic> json) {
    return ToolSearchToolResultBlock(
      toolUseId: json['tool_use_id'] as String,
      content: (json['content'] as Map).cast<String, dynamic>(),
    );
  }

  @override
  Map<String, dynamic> toJson() => {
    'type': 'tool_search_tool_result',
    'tool_use_id': toolUseId,
    'content': content,
  };

  /// Creates a copy with replaced values.
  ToolSearchToolResultBlock copyWith({
    String? toolUseId,
    Map<String, dynamic>? content,
  }) {
    return ToolSearchToolResultBlock(
      toolUseId: toolUseId ?? this.toolUseId,
      content: content ?? this.content,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ToolSearchToolResultBlock &&
          runtimeType == other.runtimeType &&
          toolUseId == other.toolUseId &&
          mapsEqual(content, other.content);

  @override
  int get hashCode => Object.hash(toolUseId, mapHash(content));

  @override
  String toString() =>
      'ToolSearchToolResultBlock(toolUseId: $toolUseId, content: $content)';
}

/// Container upload content block.
@immutable
class ContainerUploadBlock extends ContentBlock {
  /// Uploaded file ID.
  final String fileId;

  /// Creates a [ContainerUploadBlock].
  const ContainerUploadBlock({required this.fileId});

  /// Creates a [ContainerUploadBlock] from JSON.
  factory ContainerUploadBlock.fromJson(Map<String, dynamic> json) {
    return ContainerUploadBlock(fileId: json['file_id'] as String);
  }

  @override
  Map<String, dynamic> toJson() => {
    'type': 'container_upload',
    'file_id': fileId,
  };

  /// Creates a copy with replaced values.
  ContainerUploadBlock copyWith({String? fileId}) {
    return ContainerUploadBlock(fileId: fileId ?? this.fileId);
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContainerUploadBlock &&
          runtimeType == other.runtimeType &&
          fileId == other.fileId;

  @override
  int get hashCode => fileId.hashCode;

  @override
  String toString() => 'ContainerUploadBlock(fileId: $fileId)';
}

/// Compaction content block (beta).
///
/// Returned when server-side compaction is triggered. Can be round-tripped
/// back to subsequent requests to preserve compacted context.
@immutable
class CompactionBlock extends ContentBlock {
  /// Summary content for compacted context.
  ///
  /// When `null`, compaction failed and the block is a no-op if round-tripped.
  final String? content;

  /// Encrypted compaction payload for server-side context restoration.
  final String? encryptedContent;

  /// Creates a [CompactionBlock].
  const CompactionBlock({required this.content, this.encryptedContent});

  /// Creates a [CompactionBlock] from JSON.
  factory CompactionBlock.fromJson(Map<String, dynamic> json) {
    return CompactionBlock(
      content: json['content'] as String?,
      encryptedContent: json['encrypted_content'] as String?,
    );
  }

  @override
  Map<String, dynamic> toJson() => {
    'type': 'compaction',
    'content': content,
    'encrypted_content': encryptedContent,
  };

  /// Creates a copy with replaced values.
  CompactionBlock copyWith({
    Object? content = unsetCopyWithValue,
    Object? encryptedContent = unsetCopyWithValue,
  }) {
    return CompactionBlock(
      content: content == unsetCopyWithValue
          ? this.content
          : content as String?,
      encryptedContent: encryptedContent == unsetCopyWithValue
          ? this.encryptedContent
          : encryptedContent as String?,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompactionBlock &&
          runtimeType == other.runtimeType &&
          content == other.content &&
          encryptedContent == other.encryptedContent;

  @override
  int get hashCode => Object.hash(content, encryptedContent);

  @override
  String toString() =>
      'CompactionBlock(content: $content, '
      'encryptedContent: ${encryptedContent == null ? 'null' : '[${encryptedContent!.length} chars]'})';
}

/// Web search result content.
sealed class WebSearchResult {
  const WebSearchResult();

  /// Creates a [WebSearchResult] from JSON.
  ///
  /// The [json] parameter accepts either a `List` (array of search result
  /// items for the success case) or a `Map` (error object with
  /// `type: "web_search_tool_result_error"`).
  factory WebSearchResult.fromJson(Object json) {
    if (json is List) {
      return WebSearchResultSuccess.fromJson(json);
    }
    if (json is Map) {
      final map = json.cast<String, dynamic>();
      final type = map['type'];
      if (type is String) {
        if (type == 'web_search_tool_result_error') {
          return WebSearchResultError.fromJson(map);
        }
        throw FormatException('Unknown WebSearchResult type: $type');
      }
      throw const FormatException(
        'Invalid WebSearchResult: "type" must be a string',
      );
    }
    throw FormatException(
      'Expected List or Map for WebSearchResult, got ${json.runtimeType}',
    );
  }

  /// Converts to JSON.
  Object toJson();
}

/// Successful web search result.
@immutable
class WebSearchResultSuccess extends WebSearchResult {
  /// The search results.
  final List<WebSearchResultItem> results;

  /// Creates a [WebSearchResultSuccess].
  const WebSearchResultSuccess({required this.results});

  /// Creates a [WebSearchResultSuccess] from a JSON array of result items.
  factory WebSearchResultSuccess.fromJson(List<dynamic> json) {
    return WebSearchResultSuccess(
      results: json
          .map((e) => WebSearchResultItem.fromJson(e as Map<String, dynamic>))
          .toList(),
    );
  }

  @override
  List<Map<String, dynamic>> toJson() =>
      results.map((e) => e.toJson()).toList();

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebSearchResultSuccess &&
          runtimeType == other.runtimeType &&
          listsEqual(results, other.results);

  @override
  int get hashCode => listHash(results);

  @override
  String toString() => 'WebSearchResultSuccess(results: $results)';
}

/// A single web search result item.
@immutable
class WebSearchResultItem {
  /// URL of the search result.
  final String url;

  /// Title of the search result.
  final String title;

  /// Encrypted content for citations.
  final String? encryptedContent;

  /// Page age information.
  final String? pageAge;

  /// Creates a [WebSearchResultItem].
  const WebSearchResultItem({
    required this.url,
    required this.title,
    this.encryptedContent,
    this.pageAge,
  });

  /// Creates a [WebSearchResultItem] from JSON.
  factory WebSearchResultItem.fromJson(Map<String, dynamic> json) {
    return WebSearchResultItem(
      url: json['url'] as String,
      title: json['title'] as String,
      encryptedContent: json['encrypted_content'] as String?,
      pageAge: json['page_age'] as String?,
    );
  }

  /// Converts to JSON.
  Map<String, dynamic> toJson() => {
    'type': 'web_search_result',
    'url': url,
    'title': title,
    if (encryptedContent != null) 'encrypted_content': encryptedContent,
    if (pageAge != null) 'page_age': pageAge,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebSearchResultItem &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          title == other.title &&
          encryptedContent == other.encryptedContent &&
          pageAge == other.pageAge;

  @override
  int get hashCode => Object.hash(url, title, encryptedContent, pageAge);

  @override
  String toString() =>
      'WebSearchResultItem(url: $url, title: $title, '
      'encryptedContent: $encryptedContent, pageAge: $pageAge)';
}

/// Web search error result.
@immutable
class WebSearchResultError extends WebSearchResult {
  /// Error code.
  final String errorCode;

  /// Creates a [WebSearchResultError].
  const WebSearchResultError({required this.errorCode});

  /// Creates a [WebSearchResultError] from JSON.
  factory WebSearchResultError.fromJson(Map<String, dynamic> json) {
    return WebSearchResultError(errorCode: json['error_code'] as String);
  }

  @override
  Map<String, dynamic> toJson() => {
    'type': 'web_search_tool_result_error',
    'error_code': errorCode,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebSearchResultError &&
          runtimeType == other.runtimeType &&
          errorCode == other.errorCode;

  @override
  int get hashCode => errorCode.hashCode;

  @override
  String toString() => 'WebSearchResultError(errorCode: $errorCode)';
}

/// Citation for text content.
sealed class Citation {
  const Citation();

  /// Creates a [Citation] from JSON.
  factory Citation.fromJson(Map<String, dynamic> json) {
    final type = json['type'] as String;
    return switch (type) {
      'char_location' => CharLocationCitation.fromJson(json),
      'page_location' => PageLocationCitation.fromJson(json),
      'content_block_location' => ContentBlockLocationCitation.fromJson(json),
      'web_search_result_location' => WebSearchResultLocationCitation.fromJson(
        json,
      ),
      _ => throw FormatException('Unknown Citation type: $type'),
    };
  }

  /// Converts to JSON.
  Map<String, dynamic> toJson();
}

/// Citation with character location (for plain text sources).
@immutable
class CharLocationCitation extends Citation {
  /// The cited text.
  final String citedText;

  /// The document index.
  final int documentIndex;

  /// The document title.
  final String? documentTitle;

  /// Start character offset.
  final int startCharIndex;

  /// End character offset.
  final int endCharIndex;

  /// Creates a [CharLocationCitation].
  const CharLocationCitation({
    required this.citedText,
    required this.documentIndex,
    this.documentTitle,
    required this.startCharIndex,
    required this.endCharIndex,
  });

  /// Creates a [CharLocationCitation] from JSON.
  factory CharLocationCitation.fromJson(Map<String, dynamic> json) {
    return CharLocationCitation(
      citedText: json['cited_text'] as String,
      documentIndex: json['document_index'] as int,
      documentTitle: json['document_title'] as String?,
      startCharIndex: json['start_char_index'] as int,
      endCharIndex: json['end_char_index'] as int,
    );
  }

  @override
  Map<String, dynamic> toJson() => {
    'type': 'char_location',
    'cited_text': citedText,
    'document_index': documentIndex,
    if (documentTitle != null) 'document_title': documentTitle,
    'start_char_index': startCharIndex,
    'end_char_index': endCharIndex,
  };

  /// Creates a copy with replaced values.
  CharLocationCitation copyWith({
    String? citedText,
    int? documentIndex,
    Object? documentTitle = unsetCopyWithValue,
    int? startCharIndex,
    int? endCharIndex,
  }) {
    return CharLocationCitation(
      citedText: citedText ?? this.citedText,
      documentIndex: documentIndex ?? this.documentIndex,
      documentTitle: documentTitle == unsetCopyWithValue
          ? this.documentTitle
          : documentTitle as String?,
      startCharIndex: startCharIndex ?? this.startCharIndex,
      endCharIndex: endCharIndex ?? this.endCharIndex,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CharLocationCitation &&
          runtimeType == other.runtimeType &&
          citedText == other.citedText &&
          documentIndex == other.documentIndex &&
          documentTitle == other.documentTitle &&
          startCharIndex == other.startCharIndex &&
          endCharIndex == other.endCharIndex;

  @override
  int get hashCode => Object.hash(
    citedText,
    documentIndex,
    documentTitle,
    startCharIndex,
    endCharIndex,
  );

  @override
  String toString() =>
      'CharLocationCitation(citedText: [${citedText.length} chars], '
      'documentIndex: $documentIndex, documentTitle: $documentTitle, '
      'startCharIndex: $startCharIndex, endCharIndex: $endCharIndex)';
}

/// Citation with page location (for PDF sources).
@immutable
class PageLocationCitation extends Citation {
  /// The cited text.
  final String citedText;

  /// The document index.
  final int documentIndex;

  /// The document title.
  final String? documentTitle;

  /// Start page number.
  final int startPageNumber;

  /// End page number.
  final int endPageNumber;

  /// Creates a [PageLocationCitation].
  const PageLocationCitation({
    required this.citedText,
    required this.documentIndex,
    this.documentTitle,
    required this.startPageNumber,
    required this.endPageNumber,
  });

  /// Creates a [PageLocationCitation] from JSON.
  factory PageLocationCitation.fromJson(Map<String, dynamic> json) {
    return PageLocationCitation(
      citedText: json['cited_text'] as String,
      documentIndex: json['document_index'] as int,
      documentTitle: json['document_title'] as String?,
      startPageNumber: json['start_page_number'] as int,
      endPageNumber: json['end_page_number'] as int,
    );
  }

  @override
  Map<String, dynamic> toJson() => {
    'type': 'page_location',
    'cited_text': citedText,
    'document_index': documentIndex,
    if (documentTitle != null) 'document_title': documentTitle,
    'start_page_number': startPageNumber,
    'end_page_number': endPageNumber,
  };

  /// Creates a copy with replaced values.
  PageLocationCitation copyWith({
    String? citedText,
    int? documentIndex,
    Object? documentTitle = unsetCopyWithValue,
    int? startPageNumber,
    int? endPageNumber,
  }) {
    return PageLocationCitation(
      citedText: citedText ?? this.citedText,
      documentIndex: documentIndex ?? this.documentIndex,
      documentTitle: documentTitle == unsetCopyWithValue
          ? this.documentTitle
          : documentTitle as String?,
      startPageNumber: startPageNumber ?? this.startPageNumber,
      endPageNumber: endPageNumber ?? this.endPageNumber,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PageLocationCitation &&
          runtimeType == other.runtimeType &&
          citedText == other.citedText &&
          documentIndex == other.documentIndex &&
          documentTitle == other.documentTitle &&
          startPageNumber == other.startPageNumber &&
          endPageNumber == other.endPageNumber;

  @override
  int get hashCode => Object.hash(
    citedText,
    documentIndex,
    documentTitle,
    startPageNumber,
    endPageNumber,
  );

  @override
  String toString() =>
      'PageLocationCitation(citedText: [${citedText.length} chars], '
      'documentIndex: $documentIndex, documentTitle: $documentTitle, '
      'startPageNumber: $startPageNumber, endPageNumber: $endPageNumber)';
}

/// Citation with content block location.
@immutable
class ContentBlockLocationCitation extends Citation {
  /// The cited text.
  final String citedText;

  /// The document index.
  final int documentIndex;

  /// The document title.
  final String? documentTitle;

  /// Start content block index.
  final int startBlockIndex;

  /// End content block index.
  final int endBlockIndex;

  /// Creates a [ContentBlockLocationCitation].
  const ContentBlockLocationCitation({
    required this.citedText,
    required this.documentIndex,
    this.documentTitle,
    required this.startBlockIndex,
    required this.endBlockIndex,
  });

  /// Creates a [ContentBlockLocationCitation] from JSON.
  factory ContentBlockLocationCitation.fromJson(Map<String, dynamic> json) {
    return ContentBlockLocationCitation(
      citedText: json['cited_text'] as String,
      documentIndex: json['document_index'] as int,
      documentTitle: json['document_title'] as String?,
      startBlockIndex: json['start_block_index'] as int,
      endBlockIndex: json['end_block_index'] as int,
    );
  }

  @override
  Map<String, dynamic> toJson() => {
    'type': 'content_block_location',
    'cited_text': citedText,
    'document_index': documentIndex,
    if (documentTitle != null) 'document_title': documentTitle,
    'start_block_index': startBlockIndex,
    'end_block_index': endBlockIndex,
  };

  /// Creates a copy with replaced values.
  ContentBlockLocationCitation copyWith({
    String? citedText,
    int? documentIndex,
    Object? documentTitle = unsetCopyWithValue,
    int? startBlockIndex,
    int? endBlockIndex,
  }) {
    return ContentBlockLocationCitation(
      citedText: citedText ?? this.citedText,
      documentIndex: documentIndex ?? this.documentIndex,
      documentTitle: documentTitle == unsetCopyWithValue
          ? this.documentTitle
          : documentTitle as String?,
      startBlockIndex: startBlockIndex ?? this.startBlockIndex,
      endBlockIndex: endBlockIndex ?? this.endBlockIndex,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ContentBlockLocationCitation &&
          runtimeType == other.runtimeType &&
          citedText == other.citedText &&
          documentIndex == other.documentIndex &&
          documentTitle == other.documentTitle &&
          startBlockIndex == other.startBlockIndex &&
          endBlockIndex == other.endBlockIndex;

  @override
  int get hashCode => Object.hash(
    citedText,
    documentIndex,
    documentTitle,
    startBlockIndex,
    endBlockIndex,
  );

  @override
  String toString() =>
      'ContentBlockLocationCitation(citedText: [${citedText.length} chars], '
      'documentIndex: $documentIndex, documentTitle: $documentTitle, '
      'startBlockIndex: $startBlockIndex, endBlockIndex: $endBlockIndex)';
}

/// Citation from web search result.
@immutable
class WebSearchResultLocationCitation extends Citation {
  /// The cited text.
  final String citedText;

  /// Encrypted index for the citation.
  final String encryptedIndex;

  /// Title of the source.
  final String? title;

  /// URL of the source.
  final String? url;

  /// Creates a [WebSearchResultLocationCitation].
  const WebSearchResultLocationCitation({
    required this.citedText,
    required this.encryptedIndex,
    this.title,
    this.url,
  });

  /// Creates a [WebSearchResultLocationCitation] from JSON.
  factory WebSearchResultLocationCitation.fromJson(Map<String, dynamic> json) {
    return WebSearchResultLocationCitation(
      citedText: json['cited_text'] as String,
      encryptedIndex: json['encrypted_index'] as String,
      title: json['title'] as String?,
      url: json['url'] as String?,
    );
  }

  @override
  Map<String, dynamic> toJson() => {
    'type': 'web_search_result_location',
    'cited_text': citedText,
    'encrypted_index': encryptedIndex,
    if (title != null) 'title': title,
    if (url != null) 'url': url,
  };

  /// Creates a copy with replaced values.
  WebSearchResultLocationCitation copyWith({
    String? citedText,
    String? encryptedIndex,
    Object? title = unsetCopyWithValue,
    Object? url = unsetCopyWithValue,
  }) {
    return WebSearchResultLocationCitation(
      citedText: citedText ?? this.citedText,
      encryptedIndex: encryptedIndex ?? this.encryptedIndex,
      title: title == unsetCopyWithValue ? this.title : title as String?,
      url: url == unsetCopyWithValue ? this.url : url as String?,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebSearchResultLocationCitation &&
          runtimeType == other.runtimeType &&
          citedText == other.citedText &&
          encryptedIndex == other.encryptedIndex &&
          title == other.title &&
          url == other.url;

  @override
  int get hashCode => Object.hash(citedText, encryptedIndex, title, url);

  @override
  String toString() =>
      'WebSearchResultLocationCitation(citedText: [${citedText.length} chars], '
      'encryptedIndex: [${encryptedIndex.length} chars], '
      'title: $title, url: $url)';
}

// ============================================================================
// MCP Tool Content Blocks
// ============================================================================

/// MCP tool use block in a response.
///
/// Represents a model-initiated tool call to an MCP server tool.
@immutable
class MCPToolUseBlock extends ContentBlock {
  /// Unique identifier for this tool use.
  final String id;

  /// Name of the MCP tool being used.
  final String name;

  /// Name of the MCP server providing the tool.
  final String serverName;

  /// Input parameters for the tool.
  final Map<String, dynamic> input;

  /// Creates an [MCPToolUseBlock].
  const MCPToolUseBlock({
    required this.id,
    required this.name,
    required this.serverName,
    required this.input,
  });

  /// Creates an [MCPToolUseBlock] from JSON.
  factory MCPToolUseBlock.fromJson(Map<String, dynamic> json) {
    return MCPToolUseBlock(
      id: json['id'] as String,
      name: json['name'] as String,
      serverName: json['server_name'] as String,
      input: json['input'] as Map<String, dynamic>,
    );
  }

  @override
  Map<String, dynamic> toJson() => {
    'type': 'mcp_tool_use',
    'id': id,
    'name': name,
    'server_name': serverName,
    'input': input,
  };

  /// Creates a copy with replaced values.
  MCPToolUseBlock copyWith({
    String? id,
    String? name,
    String? serverName,
    Map<String, dynamic>? input,
  }) {
    return MCPToolUseBlock(
      id: id ?? this.id,
      name: name ?? this.name,
      serverName: serverName ?? this.serverName,
      input: input ?? this.input,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MCPToolUseBlock &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          serverName == other.serverName &&
          mapsEqual(input, other.input);

  @override
  int get hashCode => Object.hash(id, name, serverName, mapHash(input));

  @override
  String toString() =>
      'MCPToolUseBlock(id: $id, name: $name, '
      'serverName: $serverName, input: $input)';
}

/// Content of an MCP tool result — either a plain string or a list of
/// text blocks.
sealed class MCPToolResultContent {
  const MCPToolResultContent();

  /// Creates from a plain string.
  factory MCPToolResultContent.text(String text) = MCPToolResultStringContent;

  /// Creates from a list of text blocks.
  factory MCPToolResultContent.blocks(List<TextBlock> blocks) =
      MCPToolResultBlocksContent;

  /// Creates an [MCPToolResultContent] from JSON.
  factory MCPToolResultContent.fromJson(Object json) {
    if (json is String) return MCPToolResultStringContent(json);
    if (json is List) {
      return MCPToolResultBlocksContent(
        json.map((e) => TextBlock.fromJson(e as Map<String, dynamic>)).toList(),
      );
    }
    throw FormatException(
      'Expected String or List for MCPToolResultContent, '
      'got ${json.runtimeType}',
    );
  }

  /// Converts to JSON.
  Object toJson();
}

/// Plain string content for an MCP tool result.
@immutable
class MCPToolResultStringContent extends MCPToolResultContent {
  /// The text content.
  final String text;

  /// Creates an [MCPToolResultStringContent].
  const MCPToolResultStringContent(this.text);

  @override
  Object toJson() => text;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MCPToolResultStringContent &&
          runtimeType == other.runtimeType &&
          text == other.text;

  @override
  int get hashCode => text.hashCode;

  @override
  String toString() => 'MCPToolResultStringContent(${text.length} chars)';
}

/// List of text blocks content for an MCP tool result.
@immutable
class MCPToolResultBlocksContent extends MCPToolResultContent {
  /// The text blocks.
  final List<TextBlock> blocks;

  /// Creates an [MCPToolResultBlocksContent].
  const MCPToolResultBlocksContent(this.blocks);

  @override
  Object toJson() => blocks.map((b) => b.toJson()).toList();

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MCPToolResultBlocksContent &&
          runtimeType == other.runtimeType &&
          listsEqual(blocks, other.blocks);

  @override
  int get hashCode => listHash(blocks);

  @override
  String toString() => 'MCPToolResultBlocksContent(${blocks.length} blocks)';
}

/// MCP tool result block in a response.
///
/// Contains the result of an MCP tool call.
@immutable
class MCPToolResultBlock extends ContentBlock {
  /// The content of the tool result.
  final MCPToolResultContent content;

  /// Whether this result represents an error.
  final bool isError;

  /// The ID of the tool use this result corresponds to.
  final String toolUseId;

  /// Creates an [MCPToolResultBlock].
  const MCPToolResultBlock({
    required this.content,
    this.isError = false,
    required this.toolUseId,
  });

  /// Creates an [MCPToolResultBlock] from JSON.
  factory MCPToolResultBlock.fromJson(Map<String, dynamic> json) {
    return MCPToolResultBlock(
      content: MCPToolResultContent.fromJson(json['content'] as Object),
      isError: json['is_error'] as bool? ?? false,
      toolUseId: json['tool_use_id'] as String,
    );
  }

  @override
  Map<String, dynamic> toJson() => {
    'type': 'mcp_tool_result',
    'content': content.toJson(),
    'is_error': isError,
    'tool_use_id': toolUseId,
  };

  /// Creates a copy with replaced values.
  MCPToolResultBlock copyWith({
    MCPToolResultContent? content,
    bool? isError,
    String? toolUseId,
  }) {
    return MCPToolResultBlock(
      content: content ?? this.content,
      isError: isError ?? this.isError,
      toolUseId: toolUseId ?? this.toolUseId,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MCPToolResultBlock &&
          runtimeType == other.runtimeType &&
          content == other.content &&
          isError == other.isError &&
          toolUseId == other.toolUseId;

  @override
  int get hashCode => Object.hash(content, isError, toolUseId);

  @override
  String toString() =>
      'MCPToolResultBlock(content: $content, '
      'isError: $isError, toolUseId: $toolUseId)';
}

// ============================================================================
// Unknown Content Block
// ============================================================================

/// Forward-compatible fallback for unknown content block types.
///
/// Preserves the raw JSON so unrecognized blocks can be round-tripped
/// without data loss.
@immutable
class UnknownContentBlock extends ContentBlock {
  /// The raw JSON for this unknown content block.
  final Map<String, dynamic> raw;

  /// Creates an [UnknownContentBlock].
  UnknownContentBlock({required Map<String, dynamic> raw})
    : raw = Map.unmodifiable(raw);

  /// Creates an [UnknownContentBlock] from JSON.
  factory UnknownContentBlock.fromJson(Map<String, dynamic> json) {
    return UnknownContentBlock(raw: json);
  }

  @override
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(raw);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UnknownContentBlock &&
          runtimeType == other.runtimeType &&
          mapsDeepEqual(raw, other.raw);

  @override
  int get hashCode => mapDeepHashCode(raw);

  @override
  String toString() => 'UnknownContentBlock(raw: ${raw.length} entries)';
}

// ============================================================================
// Advisor Tool Result
// ============================================================================

/// Advisor tool result block.
///
/// Contains the advisor model's response to a `server_tool_use` block
/// with `name: "advisor"`. The [content] is a discriminated union of
/// [AdvisorResult], [AdvisorRedactedResult], [AdvisorToolResultError],
/// or [AdvisorToolResultUnknown] for forward compatibility.
@immutable
class AdvisorToolResultBlock extends ContentBlock {
  /// The tool use ID this result corresponds to.
  final String toolUseId;

  /// The advisor's response content.
  final AdvisorToolResultContent content;

  /// Creates an [AdvisorToolResultBlock].
  const AdvisorToolResultBlock({
    required this.toolUseId,
    required this.content,
  });

  /// Creates an [AdvisorToolResultBlock] from JSON.
  factory AdvisorToolResultBlock.fromJson(Map<String, dynamic> json) {
    return AdvisorToolResultBlock(
      toolUseId: json['tool_use_id'] as String,
      content: AdvisorToolResultContent.fromJson(
        json['content'] as Map<String, dynamic>,
      ),
    );
  }

  @override
  Map<String, dynamic> toJson() => {
    'type': 'advisor_tool_result',
    'tool_use_id': toolUseId,
    'content': content.toJson(),
  };

  /// Creates a copy with replaced values.
  AdvisorToolResultBlock copyWith({
    String? toolUseId,
    AdvisorToolResultContent? content,
  }) {
    return AdvisorToolResultBlock(
      toolUseId: toolUseId ?? this.toolUseId,
      content: content ?? this.content,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AdvisorToolResultBlock &&
          runtimeType == other.runtimeType &&
          toolUseId == other.toolUseId &&
          content == other.content;

  @override
  int get hashCode => Object.hash(toolUseId, content);

  @override
  String toString() =>
      'AdvisorToolResultBlock(toolUseId: $toolUseId, content: $content)';
}

/// Advisor tool result content.
///
/// A discriminated union keyed by `type`:
/// - [AdvisorResult] — plaintext advice (`type: "advisor_result"`).
/// - [AdvisorRedactedResult] — encrypted advice (`type: "advisor_redacted_result"`).
/// - [AdvisorToolResultError] — error (`type: "advisor_tool_result_error"`).
/// - [AdvisorToolResultUnknown] — forward-compatible fallback for unknown types.
sealed class AdvisorToolResultContent {
  const AdvisorToolResultContent();

  /// Creates an [AdvisorToolResultContent] from JSON.
  factory AdvisorToolResultContent.fromJson(Map<String, dynamic> json) {
    final type = json['type'] as String;
    return switch (type) {
      'advisor_result' => AdvisorResult.fromJson(json),
      'advisor_redacted_result' => AdvisorRedactedResult.fromJson(json),
      'advisor_tool_result_error' => AdvisorToolResultError.fromJson(json),
      _ => AdvisorToolResultUnknown.fromJson(json),
    };
  }

  /// Converts to JSON.
  Map<String, dynamic> toJson();
}

/// Plaintext advisor result.
@immutable
class AdvisorResult extends AdvisorToolResultContent {
  /// The advisor's advice text.
  final String text;

  /// Creates an [AdvisorResult].
  const AdvisorResult({required this.text});

  /// Creates an [AdvisorResult] from JSON.
  factory AdvisorResult.fromJson(Map<String, dynamic> json) {
    final type = json['type'] as String?;
    if (type != 'advisor_result') {
      throw FormatException('Expected type "advisor_result", got "$type"');
    }
    return AdvisorResult(text: json['text'] as String);
  }

  @override
  Map<String, dynamic> toJson() => {'type': 'advisor_result', 'text': text};

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AdvisorResult &&
          runtimeType == other.runtimeType &&
          text == other.text;

  @override
  int get hashCode => text.hashCode;

  /// Creates a copy with replaced values.
  AdvisorResult copyWith({String? text}) {
    return AdvisorResult(text: text ?? this.text);
  }

  @override
  String toString() => 'AdvisorResult(text: ${text.length} chars)';
}

/// Encrypted (redacted) advisor result.
@immutable
class AdvisorRedactedResult extends AdvisorToolResultContent {
  /// The opaque encrypted content blob.
  final String encryptedContent;

  /// Creates an [AdvisorRedactedResult].
  const AdvisorRedactedResult({required this.encryptedContent});

  /// Creates an [AdvisorRedactedResult] from JSON.
  factory AdvisorRedactedResult.fromJson(Map<String, dynamic> json) {
    final type = json['type'] as String?;
    if (type != 'advisor_redacted_result') {
      throw FormatException(
        'Expected type "advisor_redacted_result", got "$type"',
      );
    }
    return AdvisorRedactedResult(
      encryptedContent: json['encrypted_content'] as String,
    );
  }

  @override
  Map<String, dynamic> toJson() => {
    'type': 'advisor_redacted_result',
    'encrypted_content': encryptedContent,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AdvisorRedactedResult &&
          runtimeType == other.runtimeType &&
          encryptedContent == other.encryptedContent;

  @override
  int get hashCode => encryptedContent.hashCode;

  /// Creates a copy with replaced values.
  AdvisorRedactedResult copyWith({String? encryptedContent}) {
    return AdvisorRedactedResult(
      encryptedContent: encryptedContent ?? this.encryptedContent,
    );
  }

  @override
  String toString() =>
      'AdvisorRedactedResult(encryptedContent: '
      '[${encryptedContent.length} chars])';
}

/// Advisor tool result error.
@immutable
class AdvisorToolResultError extends AdvisorToolResultContent {
  /// The raw error code string from the API.
  ///
  /// Preserved for round-trip fidelity — unrecognized codes are stored
  /// verbatim and serialized back unchanged.
  final String rawErrorCode;

  /// The parsed error code, derived from [rawErrorCode].
  AdvisorToolResultErrorCode get errorCode =>
      AdvisorToolResultErrorCode.fromJson(rawErrorCode);

  /// Creates an [AdvisorToolResultError].
  const AdvisorToolResultError({required this.rawErrorCode});

  /// Creates an [AdvisorToolResultError] from JSON.
  factory AdvisorToolResultError.fromJson(Map<String, dynamic> json) {
    final type = json['type'] as String?;
    if (type != 'advisor_tool_result_error') {
      throw FormatException(
        'Expected type "advisor_tool_result_error", got "$type"',
      );
    }
    return AdvisorToolResultError(rawErrorCode: json['error_code'] as String);
  }

  @override
  Map<String, dynamic> toJson() => {
    'type': 'advisor_tool_result_error',
    'error_code': rawErrorCode,
  };

  /// Creates a copy with replaced values.
  AdvisorToolResultError copyWith({String? rawErrorCode}) {
    return AdvisorToolResultError(
      rawErrorCode: rawErrorCode ?? this.rawErrorCode,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AdvisorToolResultError &&
          runtimeType == other.runtimeType &&
          rawErrorCode == other.rawErrorCode;

  @override
  int get hashCode => rawErrorCode.hashCode;

  @override
  String toString() =>
      'AdvisorToolResultError(errorCode: $errorCode, '
      'rawErrorCode: $rawErrorCode)';
}

/// Forward-compatible fallback for unknown advisor result content types.
@immutable
class AdvisorToolResultUnknown extends AdvisorToolResultContent {
  /// The raw JSON for this unknown result type.
  final Map<String, dynamic> raw;

  /// Creates an [AdvisorToolResultUnknown].
  AdvisorToolResultUnknown({required Map<String, dynamic> raw})
    : raw = Map.unmodifiable(raw);

  /// Creates an [AdvisorToolResultUnknown] from JSON.
  factory AdvisorToolResultUnknown.fromJson(Map<String, dynamic> json) {
    return AdvisorToolResultUnknown(raw: json);
  }

  @override
  Map<String, dynamic> toJson() => Map<String, dynamic>.from(raw);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AdvisorToolResultUnknown &&
          runtimeType == other.runtimeType &&
          mapsDeepEqual(raw, other.raw);

  @override
  int get hashCode => mapDeepHashCode(raw);

  @override
  String toString() => 'AdvisorToolResultUnknown(raw: ${raw.length} entries)';
}

/// Error codes for advisor tool result errors.
enum AdvisorToolResultErrorCode {
  /// The advisor sub-inference timed out.
  executionTimeExceeded,

  /// The request reached the max_uses cap.
  maxUsesExceeded,

  /// The advisor sub-inference hit capacity limits.
  overloaded,

  /// The transcript exceeded the advisor model's context window.
  promptTooLong,

  /// The advisor sub-inference was rate-limited.
  tooManyRequests,

  /// Any other advisor failure.
  unavailable,

  /// Forward-compatible fallback for unrecognized error codes.
  unknown;

  /// Creates an [AdvisorToolResultErrorCode] from JSON.
  factory AdvisorToolResultErrorCode.fromJson(String value) => switch (value) {
    'execution_time_exceeded' => executionTimeExceeded,
    'max_uses_exceeded' => maxUsesExceeded,
    'overloaded' => overloaded,
    'prompt_too_long' => promptTooLong,
    'too_many_requests' => tooManyRequests,
    'unavailable' => unavailable,
    _ => unknown,
  };

  /// Converts to a known JSON string.
  ///
  /// Returns `'unknown'` for [unknown] — this is lossy for unrecognized codes.
  /// For round-trip serialization, use [AdvisorToolResultError.rawErrorCode]
  /// instead of `errorCode.toJson()`.
  String toJson() => switch (this) {
    executionTimeExceeded => 'execution_time_exceeded',
    maxUsesExceeded => 'max_uses_exceeded',
    overloaded => 'overloaded',
    promptTooLong => 'prompt_too_long',
    tooManyRequests => 'too_many_requests',
    unavailable => 'unavailable',
    unknown => 'unknown',
  };
}
