import 'package:meta/meta.dart';

import '../common/equality_helpers.dart';
import '../metadata/finish_reason.dart';
import '../tools/tool_call.dart';

/// A choice delta in a streaming chat completion response.
@immutable
class ChatChoiceDelta {
  /// The index of this choice in the list of choices.
  final int index;

  /// The delta content generated by the model.
  final DeltaContent delta;

  /// The reason the model stopped generating (only in final chunk).
  final FinishReason? finishReason;

  /// Creates a [ChatChoiceDelta].
  const ChatChoiceDelta({
    required this.index,
    required this.delta,
    this.finishReason,
  });

  /// Creates a [ChatChoiceDelta] from JSON.
  factory ChatChoiceDelta.fromJson(Map<String, dynamic> json) =>
      ChatChoiceDelta(
        index: json['index'] as int? ?? 0,
        delta: DeltaContent.fromJson(
          json['delta'] as Map<String, dynamic>? ?? {},
        ),
        finishReason: finishReasonFromString(json['finish_reason'] as String?),
      );

  /// Converts to JSON.
  Map<String, dynamic> toJson() => {
    'index': index,
    'delta': delta.toJson(),
    if (finishReason != null)
      'finish_reason': finishReasonToString(finishReason!),
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatChoiceDelta &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          delta == other.delta &&
          finishReason == other.finishReason;

  @override
  int get hashCode => Object.hash(index, delta, finishReason);

  @override
  String toString() =>
      'ChatChoiceDelta(index: $index, delta: $delta, '
      'finishReason: $finishReason)';
}

/// Delta content in a streaming response.
@immutable
class DeltaContent {
  /// The role of the message (usually only in first chunk).
  final String? role;

  /// The content delta.
  final String? content;

  /// Tool calls delta.
  final List<ToolCall>? toolCalls;

  /// Creates a [DeltaContent].
  const DeltaContent({this.role, this.content, this.toolCalls});

  /// Creates a [DeltaContent] from JSON.
  factory DeltaContent.fromJson(Map<String, dynamic> json) => DeltaContent(
    role: json['role'] as String?,
    content: json['content'] as String?,
    toolCalls: (json['tool_calls'] as List?)
        ?.map((e) => ToolCall.fromJson(e as Map<String, dynamic>))
        .toList(),
  );

  /// Converts to JSON.
  Map<String, dynamic> toJson() => {
    if (role != null) 'role': role,
    if (content != null) 'content': content,
    if (toolCalls != null)
      'tool_calls': toolCalls!.map((e) => e.toJson()).toList(),
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeltaContent &&
          runtimeType == other.runtimeType &&
          role == other.role &&
          content == other.content &&
          listsEqual(toolCalls, other.toolCalls);

  @override
  int get hashCode =>
      Object.hash(role, content, Object.hashAll(toolCalls ?? []));

  @override
  String toString() =>
      'DeltaContent(role: $role, content: $content, toolCalls: $toolCalls)';
}
