import 'package:meta/meta.dart';

import '../metadata/finish_reason.dart';
import 'chat_message.dart';

/// A choice in a chat completion response.
@immutable
class ChatChoice {
  /// The index of this choice in the list of choices.
  final int index;

  /// The message generated by the model.
  final AssistantMessage message;

  /// The reason the model stopped generating.
  final FinishReason? finishReason;

  /// Creates a [ChatChoice].
  const ChatChoice({
    required this.index,
    required this.message,
    this.finishReason,
  });

  /// Creates a [ChatChoice] from JSON.
  factory ChatChoice.fromJson(Map<String, dynamic> json) => ChatChoice(
    index: json['index'] as int? ?? 0,
    message: AssistantMessage.fromJson(
      json['message'] as Map<String, dynamic>? ?? {},
    ),
    finishReason: finishReasonFromString(json['finish_reason'] as String?),
  );

  /// Converts to JSON.
  Map<String, dynamic> toJson() => {
    'index': index,
    'message': message.toJson(),
    if (finishReason != null)
      'finish_reason': finishReasonToString(finishReason!),
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatChoice &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          message == other.message &&
          finishReason == other.finishReason;

  @override
  int get hashCode => Object.hash(index, message, finishReason);

  @override
  String toString() =>
      'ChatChoice(index: $index, message: $message, '
      'finishReason: $finishReason)';
}
