import '../copy_with_sentinel.dart';

/// Code execution language.
enum Language {
  /// Unspecified language.
  unspecified,

  /// Python.
  python,
}

/// Code generated by the model that is meant to be executed.
class ExecutableCode {
  /// Optional unique ID of the executable code.
  final String? id;

  /// Programming language of the code.
  final Language language;

  /// The code to execute.
  final String code;

  /// Creates an [ExecutableCode].
  const ExecutableCode({this.id, required this.language, required this.code});

  /// Creates an [ExecutableCode] from JSON.
  factory ExecutableCode.fromJson(Map<String, dynamic> json) => ExecutableCode(
    id: json['id'] as String?,
    language: _languageFromString(json['language'] as String?),
    code: json['code'] as String,
  );

  /// Converts to JSON.
  Map<String, dynamic> toJson() => {
    if (id != null) 'id': id,
    'language': _languageToString(language),
    'code': code,
  };

  /// Creates a copy with replaced values.
  ExecutableCode copyWith({
    Object? id = unsetCopyWithValue,
    Object? language = unsetCopyWithValue,
    Object? code = unsetCopyWithValue,
  }) {
    return ExecutableCode(
      id: id == unsetCopyWithValue ? this.id : id as String?,
      language: language == unsetCopyWithValue
          ? this.language
          : language! as Language,
      code: code == unsetCopyWithValue ? this.code : code! as String,
    );
  }
}

/// Converts string to Language enum.
Language _languageFromString(String? value) {
  return switch (value?.toUpperCase()) {
    'PYTHON' => Language.python,
    _ => Language.unspecified,
  };
}

/// Converts Language enum to string.
String _languageToString(Language language) {
  return switch (language) {
    Language.python => 'PYTHON',
    Language.unspecified => 'LANGUAGE_UNSPECIFIED',
  };
}
