import 'package:meta/meta.dart';

import '../beta/config/container.dart';
import '../common/copy_with_sentinel.dart';
import '../common/equality_helpers.dart';
import '../content/content_block.dart';
import '../metadata/stop_reason.dart';
import '../metadata/usage.dart';
import 'message_role.dart';

/// A message response from the API.
@immutable
class Message {
  /// Unique object identifier.
  final String id;

  /// Object type. Always "message".
  final String type;

  /// Conversational role. Always [MessageRole.assistant] for API responses.
  final MessageRole role;

  /// Content generated by the model.
  final List<ContentBlock> content;

  /// The model that handled the request.
  final String model;

  /// The reason the model stopped generating.
  final StopReason? stopReason;

  /// Structured information about why model output stopped.
  ///
  /// This is non-null when [stopReason] is [StopReason.refusal].
  final RefusalStopDetails? stopDetails;

  /// The stop sequence that caused generation to stop, if any.
  final String? stopSequence;

  /// Token usage statistics.
  final Usage usage;

  /// Container metadata when server-side code execution was used.
  final Container? container;

  /// Creates a [Message].
  const Message({
    required this.id,
    this.type = 'message',
    this.role = MessageRole.assistant,
    required this.content,
    required this.model,
    this.stopReason,
    this.stopDetails,
    this.stopSequence,
    required this.usage,
    this.container,
  });

  /// Creates a [Message] from JSON.
  factory Message.fromJson(Map<String, dynamic> json) {
    return Message(
      id: json['id'] as String,
      type: json['type'] as String? ?? 'message',
      role: json['role'] != null
          ? MessageRole.fromJson(json['role'] as String)
          : MessageRole.assistant,
      content: (json['content'] as List)
          .map((e) => ContentBlock.fromJson(e as Map<String, dynamic>))
          .toList(),
      model: json['model'] as String,
      stopReason: json['stop_reason'] != null
          ? StopReason.fromJson(json['stop_reason'] as String)
          : null,
      stopDetails: json['stop_details'] != null
          ? RefusalStopDetails.fromJson(
              json['stop_details'] as Map<String, dynamic>,
            )
          : null,
      stopSequence: json['stop_sequence'] as String?,
      usage: Usage.fromJson(json['usage'] as Map<String, dynamic>),
      container: json['container'] != null
          ? Container.fromJson(json['container'] as Map<String, dynamic>)
          : null,
    );
  }

  /// Converts to JSON.
  Map<String, dynamic> toJson() => {
    'id': id,
    'type': type,
    'role': role.toJson(),
    'content': content.map((e) => e.toJson()).toList(),
    'model': model,
    if (stopReason != null) 'stop_reason': stopReason!.toJson(),
    if (stopDetails != null) 'stop_details': stopDetails!.toJson(),
    if (stopSequence != null) 'stop_sequence': stopSequence,
    'usage': usage.toJson(),
    if (container != null) 'container': container!.toJson(),
  };

  /// Creates a copy with replaced values.
  Message copyWith({
    String? id,
    String? type,
    MessageRole? role,
    List<ContentBlock>? content,
    String? model,
    Object? stopReason = unsetCopyWithValue,
    Object? stopDetails = unsetCopyWithValue,
    Object? stopSequence = unsetCopyWithValue,
    Usage? usage,
    Object? container = unsetCopyWithValue,
  }) {
    return Message(
      id: id ?? this.id,
      type: type ?? this.type,
      role: role ?? this.role,
      content: content ?? this.content,
      model: model ?? this.model,
      stopReason: stopReason == unsetCopyWithValue
          ? this.stopReason
          : stopReason as StopReason?,
      stopDetails: stopDetails == unsetCopyWithValue
          ? this.stopDetails
          : stopDetails as RefusalStopDetails?,
      stopSequence: stopSequence == unsetCopyWithValue
          ? this.stopSequence
          : stopSequence as String?,
      usage: usage ?? this.usage,
      container: container == unsetCopyWithValue
          ? this.container
          : container as Container?,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Message &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          type == other.type &&
          role == other.role &&
          listsEqual(content, other.content) &&
          model == other.model &&
          stopReason == other.stopReason &&
          stopDetails == other.stopDetails &&
          stopSequence == other.stopSequence &&
          usage == other.usage &&
          container == other.container;

  @override
  int get hashCode => Object.hash(
    id,
    type,
    role,
    listHash(content),
    model,
    stopReason,
    stopDetails,
    stopSequence,
    usage,
    container,
  );

  @override
  String toString() =>
      'Message(id: $id, type: $type, role: $role, '
      'content: $content, model: $model, stopReason: $stopReason, '
      'stopDetails: $stopDetails, stopSequence: $stopSequence, '
      'usage: $usage, container: $container)';
}
